# Generated by Django 2.2.1 on 2019-06-01 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190601_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidaytimeform',
            old_name='holiday_date',
            new_name='holidaydate',
        ),
    ]
